spring.application.name=teacher-api
spring.datasource.url=jdbc:postgresql://localhost:5432/teacher_db 
spring.datasource.username=postgres
spring.datasource.password=suvam123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true