spring.application.name=teacher-api
spring.datasource.url=jdbc:postgresql://localhost:5432/teacher_db
spring.datasource.username=postgres
spring.datasource.password=suvam123

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}