package com.suvam.teacherapi.controller;

import com.suvam.teacherapi.dto.TeacherRequestDTO;
import com.suvam.teacherapi.dto.TeacherResponseDTO;
import com.suvam.teacherapi.exception.ErrorResponse;
import com.suvam.teacherapi.model.Teacher;
import com.suvam.teacherapi.service.TeacherService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/v1/teachers")
public class TeacherController {

    private final TeacherService service;

    public TeacherController(TeacherService service) {
        this.service = service;
    }

    @PostMapping
    @Operation(
            summary = "Add teacher",
            description = "Creates a new teacher record. The client must not supply an id — it is generated by the database."
    )
    @ApiResponse(
            responseCode = "200",
            description = "Creation succeeded"
    )
    @ApiResponse(
            responseCode = "400",
            description = "You need to fill valid fields",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<TeacherResponseDTO> addTeacher(
            @Valid
            @RequestBody TeacherRequestDTO request) {
        return ResponseEntity.ok(service.addTeacher(request));
    }

    @Operation(
            summary = "Get all teachers",
            description = "Returns a list of all teachers currently stored. Returns an empty list if none exist."
    )
    @ApiResponse(
            responseCode = "200",
            description = "List retrieved successfully"
    )
    @GetMapping
    public ResponseEntity<List<TeacherResponseDTO>> getAllTeachers() {
        return ResponseEntity.ok(service.getAllTeachers());
    }

    @GetMapping("/{id}")
    @Operation(
            summary = "Get a teacher by ID",
            description = "You will get a single teacher once after you enter integer id. " +
                    "Make sure that it don't accept other characters except int number."

    )
    @ApiResponse(
            responseCode ="200",
            description = "Teacher successfully found"
    )
    @ApiResponse(
            responseCode = "400",
            description = "You entered wrong id type",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<TeacherResponseDTO> getTeacher(@PathVariable long id) {
        return ResponseEntity.ok(service.getTeacher(id));
    }

    @PutMapping("/{id}")
    public ResponseEntity<TeacherResponseDTO> updateTeacher(
            @PathVariable long id,
            @RequestBody TeacherRequestDTO request) {
        return ResponseEntity.ok(service.updateTeacher(id, request));
    }

    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteTeacher(@PathVariable long id) {
        service.deleteTeacher(id);
        return ResponseEntity.noContent().build();
    }
}
