package com.suvam.teacherapi.controller;

import com.suvam.teacherapi.dto.TeacherRequestDTO;
import com.suvam.teacherapi.dto.TeacherResponseDTO;
import com.suvam.teacherapi.exception.ErrorResponse;
import com.suvam.teacherapi.service.TeacherService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import java.net.URI;
import java.util.List;

@RestController
@RequestMapping("/api/v1/teachers")
public class TeacherController {

    private final TeacherService service;

    public TeacherController(TeacherService service) {
        this.service = service;
    }

    @PostMapping
    @Operation(
            summary = "Add teacher",
            description = "Creates a new teacher record. The client must not supply an id — it is generated by the database."
    )
    @ApiResponse(
            responseCode = "201",
            description = "Creation succeeded"
    )
    @ApiResponse(
            responseCode = "400",
            description = "You need to fill valid fields",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<TeacherResponseDTO> addTeacher(
            @Valid
            @RequestBody TeacherRequestDTO request) {
        TeacherResponseDTO created = service.addTeacher(request);

        URI location = ServletUriComponentsBuilder.fromCurrentRequest()
                .replaceQuery(null)
                .path("/{id}")
                .buildAndExpand(created.id())
                .toUri();

        return ResponseEntity.created(location).body(created);
    }

    @GetMapping
    @Operation(
            summary = "Get all teachers",
            description = "Returns a list of all teachers currently stored. Returns an empty list if none exist."
    )
    @ApiResponse(
            responseCode = "200",
            description = "List retrieved successfully"
    )
    public ResponseEntity<List<TeacherResponseDTO>> getAllTeachers() {
        return ResponseEntity.ok(service.getAllTeachers());
    }

    @GetMapping("/{id}")
    @Operation(
            summary = "Get a teacher by ID",
            description = "You will get a single teacher once after you enter integer id. " +
                    "Make sure that it don't accept other characters except int number."
    )
    @ApiResponse(
            responseCode ="200",
            description = "Teacher successfully found"
    )
    @ApiResponse(
            responseCode = "400",
            description = "You entered wrong id type",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    @ApiResponse(
            responseCode = "404",
            description = "Teacher not found",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<TeacherResponseDTO> getTeacher(@PathVariable long id) {
        return ResponseEntity.ok(service.getTeacher(id));
    }

    @PutMapping("/{id}")
    @Operation(
            summary = "Update an existing teacher",
            description = "Updates a teacher's details by id. All fields are required and validated."
    )
    @ApiResponse(
            responseCode = "200",
            description = "Updated successfully"
    )
    @ApiResponse(
            responseCode = "400",
            description = "Validation failed for one or more fields",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    @ApiResponse(
            responseCode = "404",
            description = "Teacher does not exist",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<TeacherResponseDTO> updateTeacher(
            @PathVariable long id,
            @Valid @RequestBody TeacherRequestDTO request) {
        return ResponseEntity.ok(service.updateTeacher(id, request));
    }

    @DeleteMapping("/{id}")
    @Operation(
            summary = "Delete a teacher",
            description = "Deletes a teacher record by id. No content is returned on success."
    )
    @ApiResponse(
            responseCode = "204",
            description = "Deleted successfully"
    )
    @ApiResponse(
            responseCode = "404",
            description = "Teacher not found",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))
    )
    public ResponseEntity<Void> deleteTeacher(@PathVariable long id) {
        service.deleteTeacher(id);
        return ResponseEntity.noContent().build();
    }
}
